# server
# options between 'dev' and 'prod'
server.env : "dev"
server.port : ":9000"

# session
session.name : "gin-rest-prisma-boilerplate-session"

# redis
redis.idle_connections : 10
redis.network_type : "tcp"
redis.address : "localhost:6379"
redis.secret_key : "secret"
redis.password : ""

# prisma
prisma.endpoint : "http://localhost:4466"